// Staff employee ID serialization. The server owns employee IDs: they are
// assigned from a per-school atomic counter (`School.staffCounter`) and are
// never generated by the frontend. Uniqueness is additionally enforced by the
// `@@unique([schoolId, employeeId])` index.

export const STAFF_PREFIX = "STF"

export function buildStaffNumber(year: number, sequence: number): string {
  if (!Number.isSafeInteger(sequence) || sequence < 1) {
    throw new Error(`Invalid staff sequence "${sequence}"`)
  }
  return `${STAFF_PREFIX}-${year}-${String(sequence).padStart(4, "0")}`
}
