// Admission number serialization. The server owns admission numbers: they are
// assigned from a per-school atomic counter (`School.admissionCounter`) and are
// never generated by the frontend. Uniqueness is additionally enforced by the
// `@@unique([schoolId, admissionNumber])` index.

export const ADMISSION_PREFIX = "ADM"

export function buildAdmissionNumber(year: number, sequence: number): string {
  if (!Number.isSafeInteger(sequence) || sequence < 1) {
    throw new Error(`Invalid admission sequence "${sequence}"`)
  }
  return `${ADMISSION_PREFIX}-${year}-${String(sequence).padStart(4, "0")}`
}