// Teacher employee ID serialization. The server owns employee IDs: they are
// assigned from a per-school atomic counter (`School.teacherCounter`) and are
// never generated by the frontend. Uniqueness is additionally enforced by the
// `@@unique([schoolId, employeeId])` index.

export const TEACHER_PREFIX = "TCH"

export function buildTeacherNumber(year: number, sequence: number): string {
  if (!Number.isSafeInteger(sequence) || sequence < 1) {
    throw new Error(`Invalid teacher sequence "${sequence}"`)
  }
  return `${TEACHER_PREFIX}-${year}-${String(sequence).padStart(4, "0")}`
}
